package src;

/**
 * Enum represents tiles to draw
 */
public enum TilesEnum {

	one( "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	two("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLLLLLLLLLLLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	three("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	four("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWLWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWLWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWLWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWLLLLLLLLLLLLLLLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	five("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLLLLWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWLLLLWWWWWLLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLLLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	six("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLLLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWLWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLLWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	seven("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	eight("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWLWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLLLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLLLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWLLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWLLWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	MINE_IMG("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"+
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWLLLLLLLWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWLLLLLLLLLWWWWWWWWWWL\n" +
					"LWWWWWWWWWWLLLLLLLLLLLWWWWWWWWWL\n" +
					"LWWWWWWWWWLLWWLLLLLLLLLWWWWWWWWL\n" +
					"LWWWWWWWWLLWWWLLLLLLLLLLWWWWWWWL\n" +
					"LWWWWWWWLLWWWWLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWWLLWWWLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWLLLWWLLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWLLLWLLLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWLLLLLLLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWLLLLLLLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWWLLLLLLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWWWWWLLLLLLLLLLLLLLLLWWWWWWWL\n" +
					"LWWWWWWWWLLLLLLLLLLLLLLWWWWWWWWL\n" +
					"LWWWWWWWWWLLLLLLLLLLLLWWWWWWWWWL\n" +
					"LWWWWWWWWWWLLLLLLLLLLWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWLLLLLLLLWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWLLLLLLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"),

	MARK_IMG("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"+
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWLLLLLLLLLLLLWWWWWWWWWWWWL\n" +
					"LWWWWWWWLRRRRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWLRRRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWLRRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWLRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWLRRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWLRRRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWWLRRRRRRRRRLWWWWWWWWWWWWL\n" +
					"LWWWWWWLLLLLLLLLLLLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWLLLLLLLLLLLLLLLLWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"),

	WRONG_MARK_IMG("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"+
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWLWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWLWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWLWWWWL\n" +
					"LWWWWWLLLLLLLLLLLLWWWWWWWLWWWWWL\n" +
					"LWWWWWWLRRRRRRRRWLWWWWWWLWWWWWWL\n" +
					"LWWWWWWWLRRRRRRRWLWWWWWLWWWWWWWL\n" +
					"LWWWWWWWWLRRRRRRRLWWWWLWWWWWWWWL\n" +
					"LWWWWWWWWWLRRRRRRLWWWLWWWWWWWWWL\n" +
					"LWWWWWWWWLRRRRRRRLWWLWWWWWWWWWWL\n" +
					"LWWWWWWWLRRRRRRRRLWLWWWWWWWWWWWL\n" +
					"LWWWWWWLRRRRRRRRRLLWWWWWWWWWWWWL\n" +
					"LWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWLWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWLWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWLWWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWLWWWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWLWWWWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWWLWWWWWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWWLWWWWWWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWWLWWWWWWWWWWLWWWWWWWWWWWWWL\n" +
					"LWWWWLWWWLLLLLLLLLLLLLLLLWWWWWWL\n" +
					"LWWWLWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWLWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWL\n" +
					"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"),

	COVER_IMG("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"+
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n" +
					"LWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"LWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"LWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"LWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"),

	NULL("LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvL\n" +
					"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n")

	;
	private String title;


	TilesEnum(String s) {
		title = s;
	}

	public String getTitle() {
		return title;
	}

	@Override
	public String toString() {
		return "TilesEnum{" +
						"title='" + title + '\'' +
						'}';
	}
}
