package src;

public enum TilesEnum {
	one( "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	MINE_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWLWWWWWWWWWLWWWWWWWWWLWWWWW\n" +
					"WWWWWWWLWWWWWWWWLWWWWWWWWLWWWWWW\n" +
					"WWWWWWWWLWWWWWWWLWWWWWWWLWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWLWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWLWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWLWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWLWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWLWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWLWLWWWWWWWWWWWWW\n" +
					"WWWWWWWLWWWWWWWLLLWWWWWWWLWWWWWW\n" +
					"WWWWWWWWLLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWLWWWWWWWLLLWWWWWWWLWWWWWW\n" +
					"WWWWWWWWWWWWWWLWLWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWLWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWLWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWLWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWLWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWLWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	MARK_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLRRRRRRRRWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLRRRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	WRONG_MARK_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWLWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWLWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWLWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWLWWWWWW\n" +
					"WWWWWWWLRRRRRRRRWLWWWWWWLWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRWLWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWLRRRRRRLWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWLWWWWWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRRLWLWWWWWWWWWWWW\n" +
					"WWWWWWWLRRRRRRRRRLLWWWWWWWWWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWLWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWLWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWLWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWLWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	COVER_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"WWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"WWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"),

	;
	private String title;


	TilesEnum(String s) {
		title = s;
	}

	public String getTitle() {
		return title;
	}

	@Override
	public String toString() {
		return "TilesEnum{" +
						"title='" + title + '\'' +
						'}';
	}
}
