package src;

public enum TilesEnum {
	one( "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	two("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLLLLLLLLLLLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	three("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	four("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWLWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWLWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWLWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWLLLLLLLLLLLLLLLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	five("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLLLLWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWLLLLWWWWWLLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLLLLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	six("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLLLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLLWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWWWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWLWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWLLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLLWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLLLLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	seven("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWLWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	eight("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +//
					"WWWWWWWWWWWLWWWWWWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLLLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLLLLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLLWWWWLLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWLLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWLLWWWWWWWWWWLLWWWWWWWWWW\n" +
					"WWWWWWWWWLLWWWWWWWWLLWWWWWWWWWWW\n" +
					"WWWWWWWWWWLLWWWWWWLLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),
	MINE_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWLWWWWWWWWWLWWWWWWWWWLWWWWW\n" +
					"WWWWWWWLWWWWWWWWLWWWWWWWWLWWWWWW\n" +
					"WWWWWWWWLWWWWWWWLWWWWWWWLWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWLWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWLWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWLWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWLWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWLWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWLWLWWWWWWWWWWWWW\n" +
					"WWWWWWWLWWWWWWWLLLWWWWWWWLWWWWWW\n" +
					"WWWWWWWWLLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWLWWWWWWWLLLWWWWWWWLWWWWWW\n" +
					"WWWWWWWWWWWWWWLWLWLWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWLWWLWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWLWWWLWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWLWWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWLWWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWLWWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	MARK_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLRRRRRRRRWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLRRRRRRRRRLWWWWWWWWWWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	WRONG_MARK_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWLWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWLWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWLWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWLWWWWWW\n" +
					"WWWWWWWLRRRRRRRRWLWWWWWWLWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRWLWWWWWLWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWWWLWWWWWWWWW\n" +
					"WWWWWWWWWWLRRRRRRLWWWLWWWWWWWWWW\n" +
					"WWWWWWWWWLRRRRRRRLWWLWWWWWWWWWWW\n" +
					"WWWWWWWWLRRRRRRRRLWLWWWWWWWWWWWW\n" +
					"WWWWWWWLRRRRRRRRRLLWWWWWWWWWWWWW\n" +
					"WWWWWWLLLLLLLLLLLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWLLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWLWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWLWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWLWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWLWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWLWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWLWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWLWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWWLWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWWLWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWWLWWWWWWWWWWLWWWWWWWWWWWWWW\n" +
					"WWWWWLWWWLLLLLLLLLLLLLLLLWWWWWWW\n" +
					"WWWWLWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWLWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n"),

	COVER_IMG("WWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n"+
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n" +
					"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWLLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWAAAAAAAAAAAAAAAAAAAAAAAAAALLL\n" +
					"WWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"WWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n" +
					"WWWLLLLLLLLLLLLLLLLLLLLLLLLLLLLL\n"),

	;
	private String title;


	TilesEnum(String s) {
		title = s;
	}

	public String getTitle() {
		return title;
	}

	@Override
	public String toString() {
		return "TilesEnum{" +
						"title='" + title + '\'' +
						'}';
	}
}
